"""Oracle DDL/configuration and data migration safeguards; no cloud credentials needed."""
import os
os.environ['DATABASE_MODE'] = 'external'
os.environ['DATABASE_URL'] = 'sqlite+aiosqlite:///:memory:'
os.environ['DATABASE_URL_SYNC'] = 'sqlite:///:memory:'
os.environ['SECRET_KEY'] = 'integration-tests-only-not-production'
from datetime import datetime, timezone
from hashlib import sha256
from types import SimpleNamespace
import pytest
from sqlalchemy import create_engine, create_mock_engine, select, text
from sqlalchemy.orm import Session
from app.core.database import Base
from app.core.config import Settings
from app.core.audit import AuditLog
from app.models import User, Client, Project, Lot, Sale
from app.models.document import SaleDocument, DocumentObject
from app.core.db_types import PortableJSON
from scripts.migrate_to_oracle import (backup_source, source_engine, inspect_source,
                                      copy_rows, verify_rows, normalized)
from scripts.oracle_storage import migrate_documents
from app.services.object_storage import OracleObjectStorage, StorageError


def test_oracle_ddl_has_identity_timestamps_and_only_conditional_unique_lot_index():
    statements = []
    engine = create_mock_engine('oracle+oracledb://', lambda sql, *a, **kw: statements.append(str(sql.compile(dialect=engine.dialect))))
    Base.metadata.create_all(engine)
    sql = '\n'.join(statements)
    assert 'GENERATED BY DEFAULT AS IDENTITY' in sql
    assert 'TIMESTAMP WITH TIME ZONE' in sql
    assert 'details CLOB' in sql
    assert 'uq_sales_active_lot_oracle ON sales (CASE WHEN' in sql
    assert 'CREATE UNIQUE INDEX uq_sales_active_lot ON' not in sql
    assert "'CANCELLED', 'REVERSED'" in sql
    assert 'ON DELETE RESTRICT' not in sql
    for table in Base.metadata.sorted_tables:
        if table.name not in ('document_objects', 'intake_mutex', 'crm_schema_migrations'):
            assert table.c.id.identity is not None


def test_oracle_settings_share_wallet_for_async_and_sync_and_require_secret():
    values = dict(_env_file=None, DATABASE_MODE='oracle', ORACLE_USER='CRM_TEST', ORACLE_PASSWORD='fake@:/password',
                  ORACLE_DSN='sample_low', ORACLE_CONFIG_DIR='/wallet', ORACLE_WALLET_LOCATION='/wallet',
                  ORACLE_WALLET_PASSWORD='wallet-test', SECRET_KEY='x' * 40)
    config = Settings(**values)
    assert config.DATABASE_URL == config.DATABASE_URL_SYNC == 'oracle+oracledb://@'
    assert config.database_connect_args['password'] == 'fake@:/password'
    assert config.database_connect_args['wallet_location'] == '/wallet'
    with pytest.raises(ValueError, match='SECRET_KEY'):
        Settings(**(values | {'SECRET_KEY': ''}))
    with pytest.raises(ValueError, match='ORACLE_DSN'):
        Settings(**(values | {'ORACLE_DSN': ''}))


def test_json_round_trip_oracle_unicode():
    from sqlalchemy.dialects.oracle import dialect
    kind = PortableJSON()
    payload = {'archivo': 'Titularidad José', 'ids': [1, 2]}
    assert kind.process_result_value(kind.process_bind_param(payload, dialect()), dialect()) == payload
    assert kind.process_bind_param(None, dialect()) is None


@pytest.fixture
def source(tmp_path):
    path = tmp_path / 'source.db'
    engine = create_engine('sqlite:///' + str(path))
    Base.metadata.create_all(engine)
    with Session(engine) as db:
        db.add(User(id=7, email='test@example.com', username='test', full_name='Prueba', hashed_password='unchanged-hash'))
        db.add(Project(id=5, name='Floresta', slug='floresta-campestre'))
        db.flush()
        db.add(Client(id=12, full_name='José', project_id=5))
        db.flush()
        db.add(Lot(id=23, project_id=5, block='M1', lot_number=3, area_sqm=200, price_per_sqm=800, total_price=160000))
        db.flush()
        db.add(Sale(id=34, client_id=12, lot_id=23, sale_price=160000))
        db.flush()
        payload = b'original archived file'
        db.add(SaleDocument(id=45, sale_id=34, uploaded_by=7, category='ownership', filename='documento.txt',
                            content_type='text/plain', size_bytes=len(payload), sha256=sha256(payload).hexdigest(), content=payload))
        db.add(AuditLog(action='TEST', entity_type='sale', details={'cliente': 'José', 'ids': [12]}))
        db.commit()
    yield path, engine
    engine.dispose()


def test_migration_preserves_ids_hashes_documents_and_refuses_occupied_target(source):
    _, engine = source
    target = create_engine('sqlite://')
    Base.metadata.create_all(target)
    with engine.connect() as original, target.begin() as destination:
        tables, counts = inspect_source(original, Base.metadata.sorted_tables)
        assert counts['sale_documents'] == 1
        copy_rows(original, destination, tables)
        assert destination.scalar(select(User.hashed_password)) == 'unchanged-hash'
        assert destination.scalar(select(Sale.client_id)) == 12
        assert destination.scalar(select(SaleDocument.content)) == b'original archived file'
        with pytest.raises(RuntimeError, match='ya contiene datos'):
            copy_rows(original, destination, tables)
        destination.execute(Sale.__table__.update().values(sale_price=1))
        with pytest.raises(RuntimeError, match='sales'):
            verify_rows(original, destination, tables)
    target.dispose()


def test_backup_never_overwrites_and_readonly_source_rejects_writes(source, tmp_path):
    path, engine = source
    backup = tmp_path / 'backup.db'
    backup_source(path, backup)
    assert backup.stat().st_mode & 0o777 == 0o600
    with pytest.raises(FileExistsError):
        backup_source(path, backup)
    readonly = source_engine(backup)
    with readonly.connect() as connection:
        assert connection.scalar(select(User.id)) == 7
        with pytest.raises(Exception, match='readonly'):
            connection.execute(text('DELETE FROM users'))
    readonly.dispose()


class FakeStore:
    def __init__(self):
        self.contents = {}
    def put(self, sale_id, content, mime):
        key = str(len(self.contents) + 1)
        self.contents[key] = content
        return {'namespace': 'test', 'bucket': 'private', 'object_key': key}
    def get(self, namespace, bucket, key, size, digest):
        content = self.contents[key]
        assert len(content) == size and sha256(content).hexdigest() == digest
        return content


def test_archive_export_is_resumable_and_keeps_original_bytes(source):
    _, engine = source
    store = FakeStore()
    with Session(engine) as session:
        migrate_documents(session, None, apply=False)
        assert session.get(DocumentObject, 45) is None
        migrate_documents(session, store, apply=True)
        migrate_documents(session, store, apply=True)
        assert len(store.contents) == 1
        assert session.get(SaleDocument, 45).content == b'original archived file'
        assert session.get(DocumentObject, 45).document_id == 45


def test_oci_download_checks_private_access_size_and_hash():
    from io import BytesIO
    payload = b'original'
    class Stream:
        def stream(self, *args, **kwargs):
            yield payload
    data = SimpleNamespace(raw=Stream(), close=lambda: None)
    client = SimpleNamespace(get_bucket=lambda *a: SimpleNamespace(data=SimpleNamespace(public_access_type='NoPublicAccess')),
                             get_object=lambda *a: SimpleNamespace(data=data))
    storage = OracleObjectStorage.__new__(OracleObjectStorage)
    storage.client = client
    assert storage.get('ns', 'bucket', 'key', len(payload), sha256(payload).hexdigest()) == payload
    with pytest.raises(StorageError):
        storage.get('ns', 'bucket', 'key', 1, sha256(payload).hexdigest())
    with pytest.raises(StorageError):
        storage.get('ns', 'bucket', 'key', len(payload), 'bad hash')
    client.get_bucket = lambda *a: SimpleNamespace(data=SimpleNamespace(public_access_type='ObjectRead'))
    with pytest.raises(StorageError, match='privado'):
        storage.get('ns', 'bucket', 'key', len(payload), sha256(payload).hexdigest())
