-- Oracle 19c+ initial CRM schema. Empty application schema only.
-- Generated from SQLAlchemy models; migrate_to_oracle.py applies this schema.
-- No DROP, user passwords, public access, or production activation.

CREATE TABLE users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	email VARCHAR2(255 CHAR) NOT NULL, 
	username VARCHAR2(100 CHAR) NOT NULL, 
	hashed_password VARCHAR2(255 CHAR) NOT NULL, 
	full_name VARCHAR2(255 CHAR) NOT NULL, 
	phone VARCHAR2(50 CHAR), 
	role VARCHAR(8 CHAR) NOT NULL, 
	is_active SMALLINT, 
	is_superuser SMALLINT, 
	totp_secret VARCHAR2(64 CHAR), 
	totp_enabled SMALLINT, 
	failed_login_attempts INTEGER, 
	locked_until TIMESTAMP WITH TIME ZONE, 
	last_login TIMESTAMP WITH TIME ZONE, 
	password_changed_at TIMESTAMP WITH TIME ZONE, 
	must_change_password SMALLINT, 
	created_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_username ON users (username);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE TABLE projects (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	name VARCHAR2(255 CHAR) NOT NULL, 
	slug VARCHAR2(255 CHAR) NOT NULL, 
	description CLOB, 
	location VARCHAR2(500 CHAR), 
	city VARCHAR2(255 CHAR), 
	state VARCHAR2(255 CHAR), 
	country VARCHAR2(100 CHAR), 
	price_per_sqm FLOAT NOT NULL, 
	total_lots INTEGER NOT NULL, 
	available_lots INTEGER NOT NULL, 
	sold_lots INTEGER NOT NULL, 
	status VARCHAR(9 CHAR), 
	cover_image_url VARCHAR2(500 CHAR), 
	gallery VARCHAR2(2000 CHAR), 
	created_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug)
);

CREATE TABLE intake_mutex (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE crm_schema_migrations (
	version VARCHAR2(80 CHAR) NOT NULL, 
	PRIMARY KEY (version)
);

CREATE TABLE audit_logs (
	id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY, 
	timestamp TIMESTAMP WITH TIME ZONE NOT NULL, 
	user_id INTEGER, 
	username VARCHAR2(100 CHAR), 
	action VARCHAR2(50 CHAR) NOT NULL, 
	entity_type VARCHAR2(50 CHAR) NOT NULL, 
	entity_id INTEGER, 
	ip_address VARCHAR2(45 CHAR), 
	user_agent VARCHAR2(500 CHAR), 
	details CLOB, 
	old_values CLOB, 
	new_values CLOB, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_audit_logs_timestamp ON audit_logs (timestamp);

CREATE INDEX ix_audit_logs_action ON audit_logs (action);

CREATE TABLE clients (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	project_id INTEGER, 
	full_name VARCHAR2(500 CHAR) NOT NULL, 
	email VARCHAR2(500 CHAR), 
	phone VARCHAR2(500 CHAR), 
	address VARCHAR2(1000 CHAR), 
	status VARCHAR(15 CHAR) NOT NULL, 
	lead_source VARCHAR(9 CHAR), 
	notes CLOB, 
	budget_range VARCHAR2(255 CHAR), 
	preferred_lot_size FLOAT, 
	assigned_agent_id INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(assigned_agent_id) REFERENCES users (id)
);

CREATE INDEX ix_clients_project_id ON clients (project_id);

CREATE INDEX ix_clients_assigned_agent_id ON clients (assigned_agent_id);

CREATE INDEX ix_clients_status ON clients (status);

CREATE TABLE lots (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	project_id INTEGER NOT NULL, 
	lot_number INTEGER NOT NULL, 
	block VARCHAR2(50 CHAR), 
	area_sqm FLOAT NOT NULL, 
	price_per_sqm FLOAT NOT NULL, 
	total_price FLOAT NOT NULL, 
	status VARCHAR(9 CHAR) NOT NULL, 
	map_coordinates VARCHAR2(500 CHAR), 
	sold_to_client_id INTEGER, 
	sold_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(sold_to_client_id) REFERENCES clients (id)
);

CREATE INDEX ix_lots_project_id ON lots (project_id);

CREATE INDEX ix_lots_status ON lots (status);

CREATE TABLE client_interactions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	client_id INTEGER NOT NULL, 
	user_id INTEGER, 
	interaction_type VARCHAR2(50 CHAR) NOT NULL, 
	notes CLOB, 
	channel VARCHAR2(50 CHAR), 
	metadata_json VARCHAR2(2000 CHAR), 
	created_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_client_interactions_client_id ON client_interactions (client_id);

CREATE TABLE sales (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	client_id INTEGER NOT NULL, 
	lot_id INTEGER NOT NULL, 
	agent_id INTEGER, 
	sale_price FLOAT NOT NULL, 
	down_payment FLOAT NOT NULL, 
	financing_amount FLOAT NOT NULL, 
	interest_rate FLOAT, 
	payment_terms_months INTEGER, 
	monthly_payment FLOAT, 
	status VARCHAR(15 CHAR) NOT NULL, 
	notes CLOB, 
	reservation_expires_at TIMESTAMP WITH TIME ZONE, 
	commission_percentage FLOAT, 
	commission_amount FLOAT, 
	created_at TIMESTAMP WITH TIME ZONE, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(lot_id) REFERENCES lots (id), 
	FOREIGN KEY(agent_id) REFERENCES users (id)
);

CREATE INDEX ix_sales_lot_id ON sales (lot_id);

CREATE INDEX ix_sales_client_id ON sales (client_id);

CREATE UNIQUE INDEX uq_sales_active_lot_oracle ON sales (CASE WHEN ((status NOT IN ('CANCELLED', 'REVERSED'))) THEN lot_id END);

CREATE TABLE payment_plans (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	sale_id INTEGER NOT NULL, 
	client_id INTEGER NOT NULL, 
	installment_number INTEGER NOT NULL, 
	due_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	amount FLOAT NOT NULL, 
	paid_amount FLOAT, 
	is_paid SMALLINT, 
	paid_at TIMESTAMP WITH TIME ZONE, 
	late_fee FLOAT, 
	notes VARCHAR2(500 CHAR), 
	created_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(sale_id) REFERENCES sales (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id)
);

CREATE INDEX ix_payment_plans_sale_id ON payment_plans (sale_id);

CREATE INDEX ix_payment_plans_client_id ON payment_plans (client_id);

CREATE TABLE sale_documents (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	sale_id INTEGER NOT NULL, 
	category VARCHAR2(40 CHAR) NOT NULL, 
	filename VARCHAR2(255 CHAR) NOT NULL, 
	content_type VARCHAR2(120 CHAR) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	sha256 VARCHAR2(64 CHAR) NOT NULL, 
	description CLOB, 
	uploaded_by INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	content BLOB NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(sale_id) REFERENCES sales (id), 
	FOREIGN KEY(uploaded_by) REFERENCES users (id)
);

CREATE INDEX ix_sale_documents_sale_id ON sale_documents (sale_id);

CREATE TABLE payments (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	sale_id INTEGER NOT NULL, 
	payment_plan_id INTEGER, 
	amount FLOAT NOT NULL, 
	payment_method VARCHAR2(50 CHAR), 
	reference_number VARCHAR2(255 CHAR), 
	receipt_url VARCHAR2(500 CHAR), 
	notes VARCHAR2(500 CHAR), 
	paid_by VARCHAR2(255 CHAR), 
	created_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(sale_id) REFERENCES sales (id), 
	FOREIGN KEY(payment_plan_id) REFERENCES payment_plans (id)
);

CREATE INDEX ix_payments_sale_id ON payments (sale_id);

CREATE TABLE document_objects (
	document_id INTEGER NOT NULL, 
	namespace VARCHAR2(255 CHAR) NOT NULL, 
	bucket VARCHAR2(255 CHAR) NOT NULL, 
	object_key VARCHAR2(500 CHAR) NOT NULL, 
	PRIMARY KEY (document_id), 
	FOREIGN KEY(document_id) REFERENCES sale_documents (id), 
	UNIQUE (object_key)
);
